In [2]:
import pandas as pd

df_combat = pd.read_csv("csv\Combat.csv")
df_combat.head()

                 session_id  idx  time_ms          action  value
0  Analytics_Data_Attempt_1    0   110000   damaged_enemy    1.0
1  Analytics_Data_Attempt_1    1   110000   damaged_enemy    1.0
2  Analytics_Data_Attempt_1    2   134000   damaged_enemy    1.0
3  Analytics_Data_Attempt_1    3   134000   damaged_enemy    1.0
4  Analytics_Data_Attempt_1    4   136000  damaged_player    0.1

In [3]:
df_input = pd.read_csv("csv\Input.csv")
df_input.head()

                 session_id  idx  time_ms          input  value
0  Analytics_Data_Attempt_1    0    48000       use_item    NaN
1  Analytics_Data_Attempt_1    1    58000         attack    NaN
2  Analytics_Data_Attempt_1    2    69000         attack    NaN
3  Analytics_Data_Attempt_1    3    72000  primary_skill    NaN
4  Analytics_Data_Attempt_1    4    72000         attack    NaN

In [11]:
df_position =pd.read_csv("csv\Position.csv")
filtro = df_position[df_position['session_id'] == 'Analytics_Data_Attempt_65']
filtro

Empty DataFrame
Columns: [session_id, idx, time_ms, map_id, position_x, position_y, position_z]
Index: []

In [5]:
df_session = pd.read_csv("csv\Session.csv")
df_session.head()

,player_id,session_id,session_name,duration_ms,duration_str,video_start_str,video_end_str
0,P01,Analytics_Data_Attempt_1,Analytics_Data_Attempt_1,310000,00:05:10,00:00:00,00:05:10
1,P01,Analytics_Data_Attempt_2,Analytics_Data_Attempt_2,340000,00:05:40,00:05:10,00:10:50
2,P01,Analytics_Data_Attempt_3,Analytics_Data_Attempt_3,107000,00:01:47,00:10:50,00:12:37
3,P02,Analytics_Data_Attempt_4,Analytics_Data_Attempt_4,436000,00:07:16,00:12:37,00:19:53
4,P03,Analytics_Data_Attempt_5,Analytics_Data_Attempt_5,553000,00:09:13,00:19:53,00:29:06